# Generated by Django 4.2.5 on 2023-10-23 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Must be of the form GW123456_123456', regex='^GW\\d{6}_\\d{6}$')])),
                ('trigger_id', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Must be of the form S123456a', regex='^S\\d{6}[a-z]{1,2}$')])),
                ('gps_time', models.FloatField(default=1126259462.391)),
                ('h1', models.BooleanField(default=False)),
                ('l1', models.BooleanField(default=False)),
                ('v1', models.BooleanField(default=False)),
                ('k1', models.BooleanField(default=False)),
            ],
        ),
    ]
